# Generated by Django 5.1.6 on 2025-02-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remote",
            name="data",
            field=models.CharField(),
        ),
    ]
