# Generated by Django 5.1.6 on 2025-02-24 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_cart_customer_employee_product_sales_productlisting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="buyer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.product"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="product_listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.productlisting",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="sales",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.sales"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CartJunction",
        ),
    ]
