# Generated by Django 5.1.6 on 2025-02-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_remote_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remote",
            name="data",
            field=models.JSONField(),
        ),
    ]
