# Generated by Django 5.1.6 on 2025-02-24 06:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_cart_buyer_cart_product_cart_product_listing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
